"""add saved_notes table

Revision ID: 60447fb61a9c
Revises: febdc2cff33f
Create Date: 2026-05-06 00:37:52.198067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60447fb61a9c'
down_revision = 'febdc2cff33f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_notes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'note_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_notes')
    # ### end Alembic commands ###
