"""add media columns to posts

Revision ID: 62287f2f1ebe
Revises: f9ec8dc2c40f
Create Date: 2026-05-05 19:48:08.246689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62287f2f1ebe'
down_revision = 'f9ec8dc2c40f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('image_name', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('link_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('link_title', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('link_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('link_image_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('link_image_url')
        batch_op.drop_column('link_description')
        batch_op.drop_column('link_title')
        batch_op.drop_column('link_url')
        batch_op.drop_column('image_name')
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
