"""add image uploads and comments to listings bounties sessions

Revision ID: 6c4b7a04dd47
Revises: 9719bd744b0c
Create Date: 2026-05-10 19:55:06.515754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c4b7a04dd47'
down_revision = '9719bd744b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bounty_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bounty_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listing_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listing_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=256), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bounties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('image_name', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('comments_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('image_name', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('comments_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('comments_count')
        batch_op.drop_column('image_name')
        batch_op.drop_column('image_path')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('comments_count')

    with op.batch_alter_table('bounties', schema=None) as batch_op:
        batch_op.drop_column('comments_count')
        batch_op.drop_column('image_name')
        batch_op.drop_column('image_path')

    op.drop_table('session_comments')
    op.drop_table('listing_images')
    op.drop_table('listing_comments')
    op.drop_table('bounty_comments')
    # ### end Alembic commands ###
