"""add status and claimer to bounties

Revision ID: 9719bd744b0c
Revises: 98c2f0a8207b
Create Date: 2026-05-10 18:41:10.228303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9719bd744b0c'
down_revision = '98c2f0a8207b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bounties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claimer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=16), nullable=True))
        batch_op.create_foreign_key('fk_bounties_claimer_id', 'users', ['claimer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bounties', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bounties_claimer_id', type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('claimer_id')

    # ### end Alembic commands ###
