"""add content_html, file fields, and cover_image to notes

Revision ID: 98c2f0a8207b
Revises: 60447fb61a9c
Create Date: 2026-05-06 15:14:54.172703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98c2f0a8207b'
down_revision = '60447fb61a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_html', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('file_path', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('file_name', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('cover_image', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('cover_image')
        batch_op.drop_column('file_name')
        batch_op.drop_column('file_path')
        batch_op.drop_column('content_html')

    # ### end Alembic commands ###
