"""add created_at and profile_pic to users

Revision ID: d8b629b311b7
Revises: 14d7a9772ad5
Create Date: 2026-05-02 15:06:40.909968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b629b311b7'
down_revision = '14d7a9772ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
